/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogginRegisterForm.java
 *
 * Created on Dec 13, 2011, 1:11:33 AM
 */
package Client;

import Messages.RequestMessage;
import Messages.RespondMessage;
import Other.Connection;
import Other.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikola
 */
public class LogginRegisterForm extends javax.swing.JFrame {

    Socket s = null;
    String serverName;
    String portNumber;
    String usrName;
    User usr;

    public LogginRegisterForm() {
    }
    
    /** Creates new form LogginRegisterForm */

    
    public LogginRegisterForm(String serverName, String porttNumber) {
        try {
            initComponents();
            tbdPane.setEnabledAt(2, false);
            tbdPane.setEnabledAt(3, false);
            
            
            this.serverName = serverName;
            this.portNumber = porttNumber;
            
            
            
            
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation((int)(dim.getWidth()/2)- getWidth()/2, (int)(dim.getHeight()/2) - this.getHeight()/2 );
            this.setResizable(false);
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPane = new javax.swing.JTabbedPane();
        panLogin = new javax.swing.JPanel();
        btnCancelL = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsenameL = new javax.swing.JTextField();
        txtPasswordL = new javax.swing.JTextField();
        btnOkL = new javax.swing.JButton();
        txtPrezimeL = new javax.swing.JTextField();
        txtImeL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panRegister = new javax.swing.JPanel();
        btnOkR = new javax.swing.JButton();
        btnCancelR = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPasswordR = new javax.swing.JTextField();
        txtUsenameR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPrezimeR = new javax.swing.JTextField();
        txtImeR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdPane.setMaximumSize(new java.awt.Dimension(62, 44));

        btnCancelL.setText("Cancel    ");
        btnCancelL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelLActionPerformed(evt);
            }
        });

        jLabel3.setText("Password:");

        jLabel5.setText("Username:");

        txtUsenameL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsenameLActionPerformed(evt);
            }
        });

        btnOkL.setText("OK        ");
        btnOkL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkLActionPerformed(evt);
            }
        });

        txtPrezimeL.setEditable(false);
        txtPrezimeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeLActionPerformed(evt);
            }
        });

        txtImeL.setEditable(false);
        txtImeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeLActionPerformed(evt);
            }
        });

        jLabel7.setText("Prezime:");
        jLabel7.setEnabled(false);

        jLabel8.setText("Ime:");
        jLabel8.setEnabled(false);

        javax.swing.GroupLayout panLoginLayout = new javax.swing.GroupLayout(panLogin);
        panLogin.setLayout(panLoginLayout);
        panLoginLayout.setHorizontalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panLoginLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtImeL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panLoginLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrezimeL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panLoginLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtUsenameL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panLoginLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panLoginLayout.createSequentialGroup()
                                        .addComponent(btnOkL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelL))
                                    .addComponent(txtPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(114, 114, 114))
        );
        panLoginLayout.setVerticalGroup(
            panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLoginLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezimeL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsenameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(60, 60, 60)
                .addGroup(panLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelL)
                    .addComponent(btnOkL))
                .addGap(19, 19, 19))
        );

        tbdPane.addTab("Login     ", panLogin);

        btnOkR.setText("OK        ");
        btnOkR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkRActionPerformed(evt);
            }
        });

        btnCancelR.setText("Cancel    ");
        btnCancelR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRActionPerformed(evt);
            }
        });

        jLabel11.setText("Password:");

        txtUsenameR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsenameRActionPerformed(evt);
            }
        });

        jLabel12.setText("Username:");

        jLabel13.setText("Prezime:");

        txtPrezimeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeRActionPerformed(evt);
            }
        });

        txtImeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeRActionPerformed(evt);
            }
        });

        jLabel14.setText("Ime:");

        javax.swing.GroupLayout panRegisterLayout = new javax.swing.GroupLayout(panRegister);
        panRegister.setLayout(panRegisterLayout);
        panRegisterLayout.setHorizontalGroup(
            panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegisterLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtImeR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panRegisterLayout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrezimeR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtUsenameR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panRegisterLayout.createSequentialGroup()
                                        .addComponent(btnOkR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelR))
                                    .addComponent(txtPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(114, 114, 114))
        );
        panRegisterLayout.setVerticalGroup(
            panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegisterLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezimeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsenameR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(60, 60, 60)
                .addGroup(panRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelR)
                    .addComponent(btnOkR))
                .addGap(19, 19, 19))
        );

        tbdPane.addTab("Register  ", panRegister);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("To:");

        jLabel2.setText("Mess:");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh users");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Loggout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tbdPane.addTab("messages", jPanel1);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButton5.setText("Get private messages");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton5))
        );

        tbdPane.addTab("private messages", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeRActionPerformed

    }//GEN-LAST:event_txtImeRActionPerformed

    private void txtPrezimeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeRActionPerformed

    }//GEN-LAST:event_txtPrezimeRActionPerformed

    private void txtUsenameRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsenameRActionPerformed

    }//GEN-LAST:event_txtUsenameRActionPerformed

    private void btnCancelRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRActionPerformed

    }//GEN-LAST:event_btnCancelRActionPerformed

    private void btnOkRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkRActionPerformed

        try {
            //Connection conn = Connection.getConnection();
            Connection conn = new Connection();
            
            usr = new User(txtImeR.getText(),txtPrezimeR.getText(),txtUsenameR.getText(),txtPasswordR.getText());
            usrName= txtUsenameR.getText();
            RequestMessage msg = new RequestMessage("","register", usr, serverName,portNumber);      
           conn.connect(msg);
           conn.writeToServer();
            RespondMessage msgR = (RespondMessage)conn.getServerResponse();
           
            if(msgR.getStatus().equals("ok_register")){
                JOptionPane.showMessageDialog(this  , "Uspesno ste se registrovali");
                tbdPane.setEnabledAt(0, false);
                tbdPane.setEnabledAt(1, false);
                tbdPane.setEnabledAt(2, true);
                tbdPane.setEnabledAt(3, true);
                
            }else if(msgR.getStatus().equals("error_register")) {
                JOptionPane.showMessageDialog(this, "Allredy registered");
            }
            else {
                JOptionPane.showMessageDialog(this, "ERROR try again");
            }
            
            conn.close();
        } catch (IOException ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch(ClassNotFoundException e){
            
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_btnOkRActionPerformed

    private void txtImeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeLActionPerformed

    }//GEN-LAST:event_txtImeLActionPerformed

    private void txtPrezimeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeLActionPerformed

    }//GEN-LAST:event_txtPrezimeLActionPerformed

    private void btnOkLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkLActionPerformed

         try {
//            Connection conn = Connection.getConnection();
            Connection conn = new Connection();
            usr = new User(txtUsenameL.getText(), txtPasswordL.getText());
            usrName=txtUsenameL.getText();
            RequestMessage msg = new RequestMessage("","loggin", usr, serverName,portNumber);
            conn.connect(msg);
            conn.writeToServer();      
           
            RespondMessage msgR = (RespondMessage)conn.getServerResponse();
            if(msgR.getStatus().equals("ok_loggin")){
                JOptionPane.showMessageDialog(this, "Uspesno ste se logovali");
                  tbdPane.setEnabledAt(0, false);
                tbdPane.setEnabledAt(1, false);
                tbdPane.setEnabledAt(2, true);
                tbdPane.setEnabledAt(3, true);
                
              
                
                
            }else if(msgR.getStatus().equals("error_loggin")) {
                JOptionPane.showMessageDialog(this, "Allredy logged in or wrong user name or password");
            }
            else{
                JOptionPane.showMessageDialog(this, "ERROR try again");
            }
        } catch (IOException ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }catch(ClassNotFoundException e){
            
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_btnOkLActionPerformed

    
   
    
    
    
    
    private void txtUsenameLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsenameLActionPerformed

    }//GEN-LAST:event_txtUsenameLActionPerformed

    private void btnCancelLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelLActionPerformed

    }//GEN-LAST:event_btnCancelLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection conn = new Connection();
            String mess = jTextField2.getText();
            String to = jTextField1.getText();
            RequestMessage msg = null;
            if(to.equals("public")){
                 msg = new RequestMessage(mess, to, usr, serverName, portNumber);
            }
            else{
                 msg = new RequestMessage("private", usr, serverName, portNumber,mess,jTextField1.getText());
            }
           
            conn.connect(msg);
            conn.writeToServer();
            if(msg.getCommand().equals("public")){
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
             System.out.println(msgR.getStatus());
                if(msgR.getStatus().equals("ok_public")){
                    jTextArea1.setText(msgR.getMessages());
                }
                else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
            }   
            
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
            Connection conn = new Connection();
            
            RequestMessage msg = new RequestMessage("", "users", usr, serverName, portNumber);
            conn.connect(msg);
            conn.writeToServer();
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
             System.out.println(msgR.getStatus());
                if(msgR.getStatus().equals("ok_users")){
                    jTextArea2.setText(msgR.getMessages());
                    
                }else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
                
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
            Connection conn = new Connection();
            usr = new User(usrName);
            RequestMessage msg = new RequestMessage("", "getprivate", usr, serverName, portNumber);
            
            conn.connect(msg);
            conn.writeToServer();
            
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
                if(msgR.getStatus().equals("ok_getprivate")){
                    jTextArea3.setText(msgR.getMessages());
                    
                }else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
                
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            Connection conn = new Connection();
            usr = new User(usrName);
            RequestMessage msg = new RequestMessage("", "getpublic", usr, serverName, portNumber);
            
            conn.connect(msg);
            conn.writeToServer();
            
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
                if(msgR.getStatus().equals("ok_getpublic")){
                    jTextArea1.setText(msgR.getMessages());
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
                
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection conn = new Connection();
            usr = new User(usrName);
            RequestMessage msg = new RequestMessage("", "logout", usr, serverName, portNumber);
            
            conn.connect(msg);
            conn.writeToServer();
            
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
                if(msgR.getStatus().equals("ok_loggout")){
                   System.exit(0);
                    
                }else if(msgR.getStatus().equals("error_loggout")) {
                JOptionPane.showMessageDialog(this, "Error while trying to loggout");
            }
                else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
                
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Connection conn = new Connection();
            usr = new User(usrName);
            RequestMessage msg = new RequestMessage("", "logout", usr, serverName, portNumber);
            
            conn.connect(msg);
            conn.writeToServer();
            
             RespondMessage msgR = (RespondMessage)conn.getServerResponse();
                if(msgR.getStatus().equals("ok_loggout")){
                   JOptionPane.showMessageDialog(this, "Logged out");
                    tbdPane.setEnabledAt(0, true);
                tbdPane.setEnabledAt(1, true);
                tbdPane.setEnabledAt(2, false);
                tbdPane.setEnabledAt(3, false);
                    
                }else if(msgR.getStatus().equals("error_loggout")) {
                JOptionPane.showMessageDialog(this, "Error while trying to loggout");
            }
                else{
                    JOptionPane.showMessageDialog(this, "ERROR try again");
                }
                
        } catch (Exception ex) {
            Logger.getLogger(LogginRegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogginRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogginRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogginRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogginRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LogginRegisterForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelL;
    private javax.swing.JButton btnCancelR;
    private javax.swing.JButton btnOkL;
    private javax.swing.JButton btnOkR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panLogin;
    private javax.swing.JPanel panRegister;
    private javax.swing.JTabbedPane tbdPane;
    private javax.swing.JTextField txtImeL;
    private javax.swing.JTextField txtImeR;
    private javax.swing.JTextField txtPasswordL;
    private javax.swing.JTextField txtPasswordR;
    private javax.swing.JTextField txtPrezimeL;
    private javax.swing.JTextField txtPrezimeR;
    private javax.swing.JTextField txtUsenameL;
    private javax.swing.JTextField txtUsenameR;
    // End of variables declaration//GEN-END:variables
}
